### ISSUE TITLE
bargain highlight option

### ISSUE THREAD

**Issue by Lejenk** [chithakumar13/fut-trade-enhancer#19]
Hi, with the bargain highlight, could you make it so we can set how far below or above the price it highlights, for example i do shadow trading and buy players that are 500 coins above their price, so could you make it so i can highlight players only 500 above the futbin price

**Comment by Feigenstaub** [comment]
Options to adjust the value would be nice. 5% under price is cool but no profit. I would prefer to put it to 7-10% so that it's like a no-brainer to buy the highlighted cards instead of checking first how much profit it would make and if its worth to put coins into it.

Not sure what lejenk means with shadow trading but I think my comment is good placed here.
