### ISSUE TITLE
[bug] fetching prices from futbin causes ban

### ISSUE THREAD

**Issue by mbednarkiewicz** [chithakumar13/fut-trade-enhancer#8]
I recently installed this script (combined with [pageJumper](https://github.com/chithakumar13/Fifa21-PageJumper)) and after couple of searches script stopped getting prices from Futbin. It also causes error 403 when trying to access futbin which clearly indicates ban. Possibly this issue could be caused by too many price fetches in short period of time similarly to Mardaneus86's project ([futwebapp-tampermonkey](https://github.com/Mardaneus86/futwebapp-tampermonkey)) as presented in [#167](https://github.com/Mardaneus86/futwebapp-tampermonkey/issues/167). Is there a possibility to change the way in which script gets prices? Unfortunately I have static IP so I can't just reset the router.

**Comment by bendebebe** [comment]
@chithakumar13 The way to change it would be to instead of fetching by each player's definitionId one at a time, grab all of the definitionId's you want to send into an array, then send 1 single request to futbin in the form of `https://www.futbin.com/22/playerPrices?player={definitionId1}&rids={definitionId2},{definitionId3},{etc}`. [Here is an example link](https://www.futbin.com/22/playerPrices?player=242444&rids=1632368776481,229984).

I was going to fork it and do it myself but I already modified Mardaneus86's project to get his working and am a little tired - but your code looks pretty clean so it should be pretty easy for you to make that change. Hope this helps, if not feel free to ask more questions.

**Comment by chithakumar13** [comment]
fixed with latest release
